version: '3.8'

services:
  backend:
    container_name: fast_api_container
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: postgresql13_container
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/.env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
