# environment strings
DEBUG_ENV = "DEBUG"
SECRET_KEY_ENV = "SECRET_KEY"
ENVIRONMENT_FILE = ".env"
DB_CONNECTION = "DB_CONNECTION"
MIN_CONNECTIONS_COUNT_ENV = "MIN_CONNECTIONS_COUNT"
MAX_CONNECTIONS_COUNT_ENV = "MAX_CONNECTIONS_COUNT"
PROJECT_NAME_ENV = "PROJECT_NAME"
PROJECT_NAME_DESC = "apartmens-app REST API"
ALLOWED_HOSTS_ENV = "ALLOWED_HOSTS"

# EXCEPTION MESSAGES
EMAIL_TAKEN = "User with this email already exists"
INCORRECT_PASSWORD = "Incorrect password"
INCORRECT_LOGIN_INPUT = "Incorrect email or password"
NO_RECORD_WITH_ID = "Record with id: {id} does not exist"
