# environment strings
DEBUG_ENV = "DEBUG"
SECRET_KEY_ENV = "SECRET_KEY"
ENVIRONMENT_FILE = ".env"
DB_CONNECTION = "DB_CONNECTION"
MIN_CONNECTIONS_COUNT_ENV = "MIN_CONNECTIONS_COUNT"
MAX_CONNECTIONS_COUNT_ENV = "MAX_CONNECTIONS_COUNT"
