excluded: # paths to ignore during linting
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

force_cast: warning
force_unwrapping: warning
force_try:
  severity: warning

file_length:
  warning: 400
  error: 700

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
variable_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50