platform :ios, '14.0'

target 'ApartmentsAppMobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ApartmentsApp
  pod 'Alamofire'
  pod 'SwiftLint'
  pod 'SwiftyJSON'
  pod 'SDWebImageSwiftUI'
  pod 'RealmSwift', '~>10'

  target 'ApartmentsAppMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApartmentsAppMobileUITests' do
    # Pods for testing
  end

end
